langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.siliconflow.cn/v1
      api-key: sk-kgklueezfnyupqvnuclkjnzwqhjmetxcbxwzcgdhulpbezue
      model-name: moonshotai/Kimi-K2-Thinking
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.siliconflow.cn/v1
      api-key: sk-kgklueezfnyupqvnuclkjnzwqhjmetxcbxwzcgdhulpbezue
      model-name: deepseek-ai/DeepSeek-R1
      log-requests: true
      log-responses: true
    embedding-model:
      base-url: https://api.siliconflow.cn/v1
      api-key: sk-kgklueezfnyupqvnuclkjnzwqhjmetxcbxwzcgdhulpbezue
      model-name: BAAI/bge-m3
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10

  community:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    dev.langchain4j: debug

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volunteer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true